version: '3.8'

services:
    app:
      build: .
      env_file: 
        - .env
      ports: 
        - "8000:8000"
      # network_mode: bridge
      networks:
        - app-network
      extra_hosts:
        - "host.docker.internal:host-gateway"


networks:
  app-network:
    driver: bridge
      





